### ISSUE TITLE
Add #import support

### ISSUE THREAD

**Issue by vincentwinkel** [tiago154/graphql-import-files#16]
It could be awesome to add the supportt of #import, really useful for the fragments.
Example:
```gql
# File user.fragment.gql

fragment UserFragment on User {
  id
  email
}
```
```gql
# File query.user.gql

#import "./user.fragment.gql"
query user {
  user {
    ...UserFragment
  }
}
```

and then we just need to `loadFile('query.user.gql');`.

**Comment by tiago154** [comment]
Hi @vincentwinkel , thanks for the suggestion.

I implemented `#import` annotation support for the `loadFile` function.

Feel free to validate the operation by installing the version **graphql-import-files@1.2.18**
