### ISSUE TITLE
Create type declarations for Typescript

### ISSUE THREAD

**Issue by johannbuscail** [tiago154/graphql-import-files#4]

**Comment by tiago154** [comment]
Hi @johannb75.
Thanks for the suggestion. I migrated the project to typescript, thus generating the file type declaration.

**Comment by Sebastp** [comment]
Still not working with ts

**Comment by tiago154** [comment]
> Still not working with ts

Hi @Sebastp .
Could you test with version 1.0.15? I did a small change and it should work.
If it doesn't work, send us a print
